[build]
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "sh -c 'exec java -Xms32m -Xmx128m -Xss256k -XX:MaxMetaspaceSize=112m -XX:ReservedCodeCacheSize=32m -XX:+UseSerialGC -XX:+ExitOnOutOfMemoryError -jar target/sneak_shop-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod --server.address=0.0.0.0'"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
